### ISSUE TITLE
Option to disable ordinal number conversion

### ISSUE THREAD

**Issue by fersarr** [ShailChoksi/text2digits#19]
Currently:

```
>>> t2d.convert('she was the third to finish the race')
'she was the 3 to finish the race'
```
The ordinal is transformed into a cardinal. Which might be okay for some use cases, but not if you are processing the text with NLP after `t2d`. 

For example, using the online parser at http://nlp.stanford.edu:8080/parser/index.jsp, 'third' will be tagged as an adjective (`JJ`) and '3' will be tagged as a cardinal number (`CD`), which changes the meaning of the sentence and also the NLP dependency tree.

I propose we add an option to disable ordinal number conversion.

Additionally, the option could you allow you to request the transformation `second` -> `2nd` instead.

**Comment by ShailChoksi** [comment]
This would be useful. Could you put up a PR for this?

**Comment by fersarr** [comment]
Sure, I can have a look when Im back home. Thanks!

**Comment by fersarr** [comment]
Done :) I left there a few comments and proposals about the tests

**Comment by fersarr** [comment]
:)
