### ISSUE TITLE
Convert method not working with multiple numbers seperated by space

### ISSUE THREAD

**Issue by Rutgerdj** [ShailChoksi/text2digits#25]
When the input to the `convert_to_digits` function contains numbers separated by spaces, only the last number will be returned. Here are some examples:
- `t2d.convert("1234 234234  123")`
   - '123'
- `t2d.convert("twenty-one  1234 234234  123")`
   - '21123'

**Comment by ShailChoksi** [comment]
Good catch! Will look into this
