### ISSUE TITLE
zero-padded numbers get converted, breaking time format

### ISSUE THREAD

**Issue by fersarr** [ShailChoksi/text2digits#26]
What's your thought on zero-padded numbers, like times?

```
>>> t2d.convert('the meeting is at 13:04')                                                                                                                                                         
'the meeting is at 13:4'                                                                                                                                                                           
>>> t2d.convert('the meeting is at 13:00')                                                                                                                                                         
'the meeting is at 13:0'
```

I would expect these to be left as they were, so that the time format `hh:mm` is not broken.

Would you be okay with not having that behavior? We could add an option, but I think it should be the default behavior. What are your thoughts?

**Comment by ShailChoksi** [comment]
I would expect them to be left as they are as well. And if someone wants to remove the padding then it should be an option. Are you able to write up a PR for this?

**Comment by fersarr** [comment]
Added a PR @ShailChoksi :
https://github.com/ShailChoksi/text2digits/pull/27
